### ISSUE TITLE
Syntax error line 58.

### ISSUE THREAD

**Issue by datatalking** [kakshay21/sentence_embeddings#1]
def main(ptrain, ntrain, ptest, ntest, out, liblinear, ngram):
    ngram = list[int(i) for i in ngram]

This line generates an error with the error carrot pointing at the "i" in for i in ngram.

I've mostly updated this from python 2 and can share what I fixed but its giving me syntax error. Please advise.

**Comment by kakshay21** [comment]
Hey, @datatalking seems like you're trying to use `nbsvm.py`.
you can see the usage in the [notebook](https://render.githubusercontent.com/view/ipynb?commit=a89893104326eae19b065ae08c95272f284ea814&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6b616b7368617932312f73656e74656e63655f656d62656464696e67732f613839383933313034333236656165313962303635616530386339353237326632383465613831342f776f72645f746f5f73656e74656e63655f656d62656464696e672e6970796e62&nwo=kakshay21%2Fsentence_embeddings&path=word_to_sentence_embedding.ipynb&repository_id=121981023&repository_type=Repository#Supervised--evaluation)

**Comment by kakshay21** [comment]
Let me know if it doesn't work.

**Comment by kakshay21** [comment]
feel free to reopen this issue.
